// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_verifyLogin from "./routes/auth/verifyLogin.tsx";
import * as $index from "./routes/index.tsx";
import * as $ConfigSyncer from "./islands/ConfigSyncer.tsx";
import * as $Tabs from "./islands/Tabs.tsx";
import * as $TokenPersistor from "./islands/TokenPersistor.tsx";
import * as $homepage_AllGuides from "./islands/homepage/AllGuides.tsx";
import * as $homepage_TeacherDasboard from "./islands/homepage/TeacherDasboard.tsx";
import * as $homepage_YourLearning from "./islands/homepage/YourLearning.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/verifyLogin.tsx": $auth_verifyLogin,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ConfigSyncer.tsx": $ConfigSyncer,
    "./islands/Tabs.tsx": $Tabs,
    "./islands/TokenPersistor.tsx": $TokenPersistor,
    "./islands/homepage/AllGuides.tsx": $homepage_AllGuides,
    "./islands/homepage/TeacherDasboard.tsx": $homepage_TeacherDasboard,
    "./islands/homepage/YourLearning.tsx": $homepage_YourLearning,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
