services:
  learnio-frontend:
    build:
      context: apps/web
      dockerfile: Dockerfile
    ports:
      - "1001:8000"
    env_file:
      - .frontend.env

  learnio-backend:
    build:
      context: apps/api
      dockerfile: Dockerfile
    ports:
      - "1002:4000"
